### ISSUE TITLE
Breaks on relative URLs

### ISSUE THREAD

**Issue by iandees** [osmlab/ohauth#9]
It seems like the root cause of the Notes not working on osm.org after the Map controls redesign is ohauth not creating an absolute URL before computing the oauth signature.

@jfirebaugh found that switching from a relative to an absolute URL [here](https://github.com/openstreetmap/openstreetmap-website/blob/9d5b81094c69a02782faead1528ef32ffcc48aea/app/assets/javascripts/index/notes.js.erb#L257) made the posting work.

**Comment by bhousel** [comment]
⛔️ This project has been deprecated and will not receive any regular maintenance.
The preferred authentication method for OpenStreetMap <a href="https://github.com/osmlab/osm-auth/pull/93">is now OAuth2</a>, therefore this library isn't used anymore.
